version: '3'
services:
  mycat:
    container_name: mycat
    image: registry.cn-shenzhen.aliyuncs.com/cocoadel/mycat:1.6.7.5
    # restart: always
    dns: 8.8.8.8
    ports:
      - "8066:8066"
      - "9066:9066"
    volumes: 
      - ./mycat/conf/:/opt/mycat/conf/
    privileged: true